spring.application.name=stock-backend
server.port=8080
spring.profiles.active=dev
mybatis-plus.global-config.db-config.table-prefix=t_
mybatis-plus.global-config.db-config.id-type= auto

logging.level.org.springframework=INFO
# 下划线转驼峰（默认一般开启，但建议明确写）
mybatis-plus.configuration.map-underscore-to-camel-case=true
# 逻辑删除字段
mybatis-plus.global-config.db-config.logic-delete-field=deleted
# 逻辑删除值（删除后）
mybatis-plus.global-config.db-config.logic-delete-value=1
# 逻辑未删除值（正常）
mybatis-plus.global-config.db-config.logic-not-delete-value=0

lowcode.scan-packages= co.handk.backend.entity