spring.application.name=stock-backend
server.port=8080
server.servlet.context-path=/api
spring.profiles.active=dev
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
mybatis-plus.global-config.db-config.table-prefix=t_
mybatis-plus.global-config.db-config.id-type=auto
logging.level.org.springframework=INFO
# Enable underscore_to_camelCase mapping
mybatis-plus.configuration.map-underscore-to-camel-case=true
# Logical delete field
mybatis-plus.global-config.db-config.logic-delete-field=deleted
# Logical delete value
mybatis-plus.global-config.db-config.logic-delete-value=1
# Logical not-delete value
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml

app.avatar.dir=${AVATAR_DIR:./data/upload/avatar}
app.goods-image.dir=${GOODS_IMAGE_DIR:./data/upload/goods}
app.brand-image.dir=${BRAND_IMAGE_DIR:./data/upload/brand}
