$permissions = @'
(1,'基礎情報管理','MENU_BASIC','basic',1,0,'/basic',1,'info','basic/index',1,0,1,1,NOW(),NOW()),
(2,'商品情報管理','MENU_GOODS_INFO','goodsInfo',1,0,'/goodsInfo',2,'goods','goodsInfo/index',1,0,1,1,NOW(),NOW()),
(3,'在庫管理','MENU_STOCK','stock',1,0,'/stock',3,'stock','stock/index',1,0,1,1,NOW(),NOW()),
(4,'請求書管理','MENU_REQUEST','request',1,0,'/request',4,'request','request/index',1,0,1,1,NOW(),NOW()),
(5,'顧客情報管理','MENU_CUSTOMER_INFO','customerInfo',1,0,'/customerInfo',5,'customer','customerInfo/index',1,0,1,1,NOW(),NOW()),
(6,'システム管理','MENU_SYSTEM','system',1,0,'/system',6,'setting','system/index',1,0,1,1,NOW(),NOW()),

(7,'ユーザー管理','MENU_USER','basic',1,1,'/user',1,'user','user/index',1,0,1,1,NOW(),NOW()),
(8,'部署管理','MENU_DEPT','basic',1,1,'/dept',2,'dept','dept/index',1,0,1,1,NOW(),NOW()),
(9,'倉庫管理','MENU_WAREHOUSE','basic',1,1,'/warehouse',3,'warehouse','warehouse/index',1,0,1,1,NOW(),NOW()),
(10,'ロール管理','MENU_ROLE','basic',1,1,'/role',4,'role','role/index',1,0,1,1,NOW(),NOW()),
(11,'権限管理','MENU_PERMISSION','basic',1,1,'/permission',5,'lock','permission/index',1,0,1,1,NOW(),NOW()),

(12,'商品管理','MENU_GOODS','goodsInfo',1,2,'/goods',1,'goods','goods/index',1,0,1,1,NOW(),NOW()),
(13,'メーカー管理','MENU_MAKER','goodsInfo',1,2,'/maker',2,'maker','maker/index',1,0,1,1,NOW(),NOW()),
(14,'ブランド管理','MENU_BRAND','goodsInfo',1,2,'/brand',3,'brand','brand/index',1,0,1,1,NOW(),NOW()),
(15,'カテゴリ管理','MENU_CATEGORY','goodsInfo',1,2,'/category',4,'category','category/index',1,0,1,1,NOW(),NOW()),
(16,'シリーズ管理','MENU_SERIES','goodsInfo',1,2,'/series',5,'series','series/index',1,0,1,1,NOW(),NOW()),

    (17,'在庫管理','MENU_STOCK_SELF','stock',1,3,'/stock/self',1,'inventory','stock/self',1,0,1,1,NOW(),NOW()),
(18,'A組在庫管理','MENU_STOCK_A','stock',1,3,'/stock/group/a',2,'inventory','stock/group',1,0,1,1,NOW(),NOW()),
(19,'B組在庫管理','MENU_STOCK_B','stock',1,3,'/stock/group/b',3,'inventory','stock/group',1,0,1,1,NOW(),NOW()),
(20,'C組在庫管理','MENU_STOCK_C','stock',1,3,'/stock/group/c',4,'inventory','stock/group',1,0,1,1,NOW(),NOW()),
(21,'入出庫伝票','MENU_STOCK_ORDER','stock',1,3,'/stockOrder',5,'order','stockOrder/index',1,0,1,1,NOW(),NOW()),
(22,'入出庫明細','MENU_STOCK_ORDER_ITEM','stock',1,3,'/stockOrderItem',6,'orderItem','stockOrderItem/index',1,0,1,1,NOW(),NOW()),
(23,'在庫分類','MENU_STOCK_TYPE','stock',1,3,'/stockType',7,'tag','stockType/index',1,0,1,1,NOW(),NOW()),
(24,'在庫履歴','MENU_STOCK_RECORD','stock',1,3,'/stockRecord',8,'history','stockRecord/index',1,0,1,1,NOW(),NOW()),
(25,'価格履歴','MENU_PRICE_RECORD','stock',1,3,'/priceRecord',9,'price','priceRecord/index',1,0,1,1,NOW(),NOW()),

(26,'請求書管理','MENU_REQUEST_FORM','request',1,4,'/requestForm',1,'form','requestForm/index',1,0,1,1,NOW(),NOW()),
(27,'請求書明細','MENU_REQUEST_ITEM','request',1,4,'/requestItem',2,'formItem','requestItem/index',1,0,1,1,NOW(),NOW()),

(28,'顧客管理','MENU_CUSTOMER','customerInfo',1,5,'/customer',1,'customer','customer/index',1,0,1,1,NOW(),NOW()),
(29,'顧客ランク管理','MENU_CUSTOMER_LEVEL','customerInfo',1,5,'/customerLevel',2,'level','customerLevel/index',1,0,1,1,NOW(),NOW()),

(30,'システム設定','MENU_CONFIG','system',1,6,'/config',1,'config','config/index',1,0,1,1,NOW(),NOW()),
(31,'メッセージ管理','MENU_MESSAGE','system',1,6,'/message',2,'message','message/index',1,0,1,1,NOW(),NOW()),
(32,'操作ログ','MENU_OPERATE_LOG','system',1,6,'/operateLog',3,'log','operateLog/index',1,0,1,1,NOW(),NOW()),

(33,'在庫管理閲覧','DATA_STOCK_READ','stock',2,3,'/api/stock/**',1,'api','',1,0,1,1,NOW(),NOW()),
(34,'在庫管理編集','DATA_STOCK_WRITE','stock',2,3,'/api/stock/**',2,'api','',1,0,1,1,NOW(),NOW()),
    (35,'在庫閲覧','DATA_STOCK_SELF_READ','stock',2,17,'/api/stock/page',1,'api','',1,0,1,1,NOW(),NOW()),
    (36,'在庫編集','DATA_STOCK_SELF_WRITE','stock',2,17,'/api/stock/**',2,'api','',1,0,1,1,NOW(),NOW()),
(37,'A組在庫閲覧','DATA_STOCK_A_READ','stock',2,18,'/api/stock/page',1,'api','',1,0,1,1,NOW(),NOW()),
(38,'A組在庫編集','DATA_STOCK_A_WRITE','stock',2,18,'/api/stock/**',2,'api','',1,0,1,1,NOW(),NOW()),
(39,'B組在庫閲覧','DATA_STOCK_B_READ','stock',2,19,'/api/stock/page',1,'api','',1,0,1,1,NOW(),NOW()),
(40,'B組在庫編集','DATA_STOCK_B_WRITE','stock',2,19,'/api/stock/**',2,'api','',1,0,1,1,NOW(),NOW()),
(41,'C組在庫閲覧','DATA_STOCK_C_READ','stock',2,20,'/api/stock/page',1,'api','',1,0,1,1,NOW(),NOW()),
(42,'C組在庫編集','DATA_STOCK_C_WRITE','stock',2,20,'/api/stock/**',2,'api','',1,0,1,1,NOW(),NOW()),
(43,'入出庫伝票閲覧','DATA_STOCK_ORDER_READ','stock',2,21,'/api/stockOrder/**',1,'api','',1,0,1,1,NOW(),NOW()),
(44,'入出庫伝票編集','DATA_STOCK_ORDER_WRITE','stock',2,21,'/api/stockOrder/**',2,'api','',1,0,1,1,NOW(),NOW()),
(45,'入出庫明細閲覧','DATA_STOCK_ORDER_ITEM_READ','stock',2,22,'/api/stockOrderItem/**',1,'api','',1,0,1,1,NOW(),NOW()),
(46,'入出庫明細編集','DATA_STOCK_ORDER_ITEM_WRITE','stock',2,22,'/api/stockOrderItem/**',2,'api','',1,0,1,1,NOW(),NOW()),
(47,'在庫分類閲覧','DATA_STOCK_TYPE_READ','stock',2,23,'/api/stockType/**',1,'api','',1,0,1,1,NOW(),NOW()),
(48,'在庫分類編集','DATA_STOCK_TYPE_WRITE','stock',2,23,'/api/stockType/**',2,'api','',1,0,1,1,NOW(),NOW()),
(49,'在庫履歴閲覧','DATA_STOCK_RECORD_READ','stock',2,24,'/api/stockRecord/**',1,'api','',1,0,1,1,NOW(),NOW()),
(50,'在庫履歴編集','DATA_STOCK_RECORD_WRITE','stock',2,24,'/api/stockRecord/**',2,'api','',1,0,1,1,NOW(),NOW()),
(51,'価格履歴閲覧','DATA_PRICE_RECORD_READ','stock',2,25,'/api/priceRecord/**',1,'api','',1,0,1,1,NOW(),NOW()),
(52,'価格履歴編集','DATA_PRICE_RECORD_WRITE','stock',2,25,'/api/priceRecord/**',2,'api','',1,0,1,1,NOW(),NOW()),

(53,'請求書管理閲覧','DATA_REQUEST_FORM_READ','request',2,26,'/api/requestForm/**',1,'api','',1,0,1,1,NOW(),NOW()),
(54,'請求書管理編集','DATA_REQUEST_FORM_WRITE','request',2,26,'/api/requestForm/**',2,'api','',1,0,1,1,NOW(),NOW()),
(55,'請求書明細閲覧','DATA_REQUEST_ITEM_READ','request',2,27,'/api/requestItem/**',1,'api','',1,0,1,1,NOW(),NOW()),
(56,'請求書明細編集','DATA_REQUEST_ITEM_WRITE','request',2,27,'/api/requestItem/**',2,'api','',1,0,1,1,NOW(),NOW()),

(57,'顧客管理閲覧','DATA_CUSTOMER_READ','customerInfo',2,28,'/api/customer/**',1,'api','',1,0,1,1,NOW(),NOW()),
(58,'顧客管理編集','DATA_CUSTOMER_WRITE','customerInfo',2,28,'/api/customer/**',2,'api','',1,0,1,1,NOW(),NOW()),
(59,'顧客ランク管理閲覧','DATA_CUSTOMER_LEVEL_READ','customerInfo',2,29,'/api/customerLevel/**',1,'api','',1,0,1,1,NOW(),NOW()),
(60,'顧客ランク管理編集','DATA_CUSTOMER_LEVEL_WRITE','customerInfo',2,29,'/api/customerLevel/**',2,'api','',1,0,1,1,NOW(),NOW()),

(61,'システム設定閲覧','DATA_CONFIG_READ','system',2,30,'/api/config/**',1,'api','',1,0,1,1,NOW(),NOW()),
(62,'システム設定編集','DATA_CONFIG_WRITE','system',2,30,'/api/config/**',2,'api','',1,0,1,1,NOW(),NOW()),
(63,'メッセージ管理閲覧','DATA_MESSAGE_READ','system',2,31,'/api/message/**',1,'api','',1,0,1,1,NOW(),NOW()),
(64,'メッセージ管理編集','DATA_MESSAGE_WRITE','system',2,31,'/api/message/**',2,'api','',1,0,1,1,NOW(),NOW()),
(65,'操作ログ閲覧','DATA_OPERATE_LOG_READ','system',2,32,'/api/operateLog/**',1,'api','',1,0,1,1,NOW(),NOW()),
(66,'操作ログ編集','DATA_OPERATE_LOG_WRITE','system',2,32,'/api/operateLog/**',2,'api','',1,0,1,1,NOW(),NOW()),

(67,'部署管理閲覧','DATA_DEPT_READ','basic',2,8,'/api/dept/**',1,'api','',1,0,1,1,NOW(),NOW()),
(68,'部署管理編集','DATA_DEPT_WRITE','basic',2,8,'/api/dept/**',2,'api','',1,0,1,1,NOW(),NOW()),
(69,'ロール管理閲覧','DATA_ROLE_READ','basic',2,10,'/api/role/**',1,'api','',1,0,1,1,NOW(),NOW()),
(70,'ロール管理編集','DATA_ROLE_WRITE','basic',2,10,'/api/role/**',2,'api','',1,0,1,1,NOW(),NOW()),
(71,'権限管理閲覧','DATA_PERMISSION_READ','basic',2,11,'/api/permission/**',1,'api','',1,0,1,1,NOW(),NOW()),
(72,'権限管理編集','DATA_PERMISSION_WRITE','basic',2,11,'/api/permission/**',2,'api','',1,0,1,1,NOW(),NOW()),
(73,'倉庫管理閲覧','DATA_WAREHOUSE_READ','basic',2,9,'/api/warehouse/**',1,'api','',1,0,1,1,NOW(),NOW()),
(74,'倉庫管理編集','DATA_WAREHOUSE_WRITE','basic',2,9,'/api/warehouse/**',2,'api','',1,0,1,1,NOW(),NOW()),
(75,'ユーザー管理閲覧','DATA_USER_READ','basic',2,7,'/api/user/**',1,'api','',1,0,1,1,NOW(),NOW()),
(76,'ユーザー管理編集','DATA_USER_WRITE','basic',2,7,'/api/user/**',2,'api','',1,0,1,1,NOW(),NOW()),
(77,'商品管理閲覧','DATA_GOODS_READ','goodsInfo',2,12,'/api/goods/**',1,'api','',1,0,1,1,NOW(),NOW()),
(78,'商品管理編集','DATA_GOODS_WRITE','goodsInfo',2,12,'/api/goods/**',2,'api','',1,0,1,1,NOW(),NOW()),
(79,'メーカー管理閲覧','DATA_MAKER_READ','goodsInfo',2,13,'/api/maker/**',1,'api','',1,0,1,1,NOW(),NOW()),
(80,'メーカー管理編集','DATA_MAKER_WRITE','goodsInfo',2,13,'/api/maker/**',2,'api','',1,0,1,1,NOW(),NOW()),
(81,'ブランド管理閲覧','DATA_BRAND_READ','goodsInfo',2,14,'/api/brand/**',1,'api','',1,0,1,1,NOW(),NOW()),
(82,'ブランド管理編集','DATA_BRAND_WRITE','goodsInfo',2,14,'/api/brand/**',2,'api','',1,0,1,1,NOW(),NOW()),
(83,'カテゴリ管理閲覧','DATA_CATEGORY_READ','goodsInfo',2,15,'/api/category/**',1,'api','',1,0,1,1,NOW(),NOW()),
(84,'カテゴリ管理編集','DATA_CATEGORY_WRITE','goodsInfo',2,15,'/api/category/**',2,'api','',1,0,1,1,NOW(),NOW()),
(85,'シリーズ管理閲覧','DATA_SERIES_READ','goodsInfo',2,16,'/api/series/**',1,'api','',1,0,1,1,NOW(),NOW()),
(86,'シリーズ管理編集','DATA_SERIES_WRITE','goodsInfo',2,16,'/api/series/**',2,'api','',1,0,1,1,NOW(),NOW());

INSERT INTO `t_role_permission` (`id`, `role_id`, `permission_id`, `deleted`, `created_by`, `updated_by`, `create_time`, `update_time`)
SELECT id, 1, id, 0, 1, 1, NOW(), NOW()
FROM t_permission;
